### ISSUE TITLE
Menu Bar Icon Does Not Remember Its Position

### ISSUE THREAD

**Issue by zecanard** [AdguardTeam/AdGuardMiniForMac#343]
### Issue Details

* AdGuard for Safari version: 1.7.4
* Environment name and version: 13.1 (15609.1.20.111.8), Technology Preview 104
* Operating System: mac 10.15.4 Catalina
* Filters you use in AdGuard: AdGuard Base, AdGuard Mobile Ads, AdGuard Annoyances, AdBlock Warning Removal List, I Don’t Care About Cookies, EasyList Cookie List, Malware Domains, Spam404, NoCoin, AdGuard French
* Any other browser extensions you have installed:

### Expected Behavior
If I move the AdGuard icon in the macOS Menu Bar (⌘-drag), it should stay where I leave it.

### Actual Behavior
After several hours, the icon moves to the left end of the icon list.

### Additional Information
I have my menu bar set to auto-hide, so I’m not entirely certain when this happens, but I know I keep having to move it back where I want it.

**Comment by zecanard** [comment]
Very strange… This was happening a fair amount when I opened this issue, but hasn’t happened again in a few days. I’m just going to close this. Sorry for the trouble!

**Comment by Oleg-Chashko** [comment]
**zecanard**
I have the same, Menu Bar Icon Does Not Remember Its Position.

**Comment by zecanard** [comment]
Maybe I spoke too soon‽

**Comment by Oleg-Chashko** [comment]
**All I did this time was reboot my computer, but I’d rebooted multiple before, with no effect.**
[Screen Recording 2020-04-20 at 19.41.41.avi.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/4505188/Screen.Recording.2020-04-20.at.19.41.41.avi.zip)

**Comment by zecanard** [comment]
@Oleg-Chashko Thank you, that helped me figure out why it kept moving to the far-left side without relaunching. This seems to happen every time AdGuard for Safari has to redraw its icon, because you can verify it simply by toggling Safari Protection, either through the toolbar icon inside Safari, or through the Menu Bar icon itself.

I was doing a lot of online shopping when I first reported this bug, which required me to disable/re-enable AdGuard a fair amount (so that shopping portals could track my purchases), which is why I kept seeing it happen. Since I have my Menu Bar on auto-hide, I couldn’t see it _as it happened_, and therefore didn’t associate the two events.

**Comment by Oleg-Chashko** [comment]
@zecanard 
I am glad to help.

**Comment by maharjanaman** [comment]
I have this issue. Turning ad blocking for safari on and off changes the menu bar position to last. Also and the invisible item gets added each time the option gets toggle.

<img width="471" alt="Screen Shot 2020-07-21 at 23 04 05" src="https://user-images.githubusercontent.com/14164484/88086137-94d1ab80-cba6-11ea-94b1-6580ea9ae8e5.png">

<img width="358" alt="Screen Shot 2020-07-21 at 23 01 00" src="https://user-images.githubusercontent.com/14164484/88085787-0e1cce80-cba6-11ea-9150-e75ac1c69002.png">

Also, in the 2nd image, the color of menu bar icon is not quite visible when not select(in dark mode).

**Comment by zecanard** [comment]
Hadn’t noticed this had been marked as resolved. Why is it being closed? The problem still exists and hasn’t been resolved.

**Comment by tvinzz** [comment]
@zecanard, because it was fixed and will be available with next release.

**Comment by zecanard** [comment]
Still seeing this in v1.8.5, both on Catalina and after upgrading to Big Sur.

**Comment by vozersky** [comment]
@zecanard looks like it's back, we'll fix it, thanks
